# Generated by Django 5.1.9 on 2026-05-26 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.TextField()),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("twice_weekly", "Twice Weekly"),
                            ("weekly", "Weekly"),
                            ("twice_monthly", "Twice Monthly"),
                            ("monthly", "Monthly"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("last_check_time", models.DateTimeField(blank=True, null=True)),
                (
                    "due_from",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("due_to", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("streak_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "habits",
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "db_table": "habit_logs",
            },
        ),
        migrations.CreateModel(
            name="HabitTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("twice_weekly", "Twice Weekly"),
                            ("weekly", "Weekly"),
                            ("twice_monthly", "Twice Monthly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "habit_templates",
            },
        ),
        migrations.CreateModel(
            name="ListTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "list_templates",
            },
        ),
    ]
