# Generated by Django 5.1.9 on 2026-05-26 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habits",
                to="lists.habitlist",
            ),
        ),
    ]
