# Generated by Django 5.1.9 on 2026-05-26 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0002_initial"),
        ("lists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="habitlog",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="habits.habit",
            ),
        ),
        migrations.AddField(
            model_name="habitlog",
            name="list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habit_logs",
                to="lists.habitlist",
            ),
        ),
        migrations.AddField(
            model_name="habitlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="habittemplate",
            name="list_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habit_templates",
                to="habits.listtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(fields=["user_id"], name="habits_user_id_cc8eb3_idx"),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(fields=["created_at"], name="habits_created_6c59f8_idx"),
        ),
        migrations.AddIndex(
            model_name="habitlog",
            index=models.Index(
                fields=["user_id"], name="habit_logs_user_id_ea9d61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habitlog",
            index=models.Index(
                fields=["habit_id"], name="habit_logs_habit_i_a205de_idx"
            ),
        ),
    ]
