# Generated by Django 5.1.9 on 2026-05-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_seed_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
    ]
