# Generated by Django 5.1.9 on 2026-05-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_add_is_checked_to_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("as_many_as_possible", "As Many As Possible"),
                    ("daily", "Daily"),
                    ("twice_weekly", "Twice Weekly"),
                    ("weekly", "Weekly"),
                    ("twice_monthly", "Twice Monthly"),
                    ("monthly", "Monthly"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="habittemplate",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("as_many_as_possible", "As Many As Possible"),
                    ("daily", "Daily"),
                    ("twice_weekly", "Twice Weekly"),
                    ("weekly", "Weekly"),
                    ("twice_monthly", "Twice Monthly"),
                    ("monthly", "Monthly"),
                ],
                max_length=20,
            ),
        ),
    ]
